---
title: "atividade4"
author: "Ian Moreira Souza"
date: "2024-06-06"
output: html_document
---


# Pacotes

library(tidyverse)
library(rgbif)
library(ggplot2)
library(dplyr)
library (readxl)
library(psycho)
library(readxl)
library(GGally)
library(ggthemes)
library(ggpubr)
library(tidyr)
library(vegan)
library(ritis)
library(validate)
library(ggmap) 
library(maps)
library(mapdata)


?occ_data

# baixar ocorrencias
BaleiaFin_gbif <- occ_data(scientificName = "Balaenoptera physalus", 
                      hasCoordinate = TRUE,
                      hasGeospatialIssue=FALSE)

# dimensoes
dim(BaleiaFin_gbif)

# checar problemas reportados
issues_gbif <- BaleiaFin_gbif$data$issues %>% 
  unique() %>% 
  strsplit(., "[,]") %>% 
  unlist()

gbif_issues() %>% 
  data.frame() %>% 
  filter(code %in% issues_gbif)
         
BaleiaFin_gbif1 <- BaleiaFin_gbif$data %>%
  dplyr::select(scientificName, acceptedScientificName, decimalLatitude, decimalLongitude,
                issues, basisOfRecord, waterbody, occurrenceStatus, rightsHolder, 
                datasetName, recordedBy, locality) 

 BaleiaFin_gbif1 <- BaleiaFin_gbif1 %>% 
   distinct()
 
 # checar niveis dos fatores
 lapply(BaleiaFin_gbif1, unique)
 
 ##################################

 ############################
 
 # funcao para classificar ocorrencias suspeitas
 flag_outlier <- function(df, species){
   
   # funcao para classificar ocorrencias suspeitas
   # baseada no calculo do centroide de todas ocorrencias
   # indica como 'check' as ocorrencias que tem distancias até o centroide
   # acima do 90th quantil (default) das distancias calculadas
   
   dados <- df %>% 
     dplyr::filter(scientificName == species); 
   
   dados2 <- geosphere::distVincentyEllipsoid(
     dados %>%
       summarise(centr_lon = median(decimalLongitude),
                 centr_lat = median(decimalLatitude)),
     dados %>% 
       dplyr::select(decimalLongitude, decimalLatitude)
   ) %>% 
     bind_cols(dados) %>% 
     rename(dist_centroid = '...1') %>% 
     mutate(flag = ifelse(dist_centroid < quantile(dist_centroid, probs = 0.9), "OK",
                          ifelse(dist_centroid >= quantile(dist_centroid, probs = 0.90) & dist_centroid < quantile(dist_centroid, probs = 0.95), "check > Q90",
                                 ifelse(dist_centroid >= quantile(dist_centroid, probs = 0.95), "check > Q95", "OK"))))
   
   # mutate(flag = ifelse(dist_centroid > quantile(dist_centroid, probs = prob), "check", "OK"))
   
   print(dados2)
   
 }
 
 # classificar ocorrências
 marcados <- BaleiaFin_gbif$data %>% 
   data.frame() %>% 
   dplyr::select(scientificName, decimalLongitude, decimalLatitude, datasetName) %>% 
   distinct()


world <- map_data('world')
 
 # mapa
 ggplot() +
   geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
   coord_fixed() +
   theme_classic() +
   geom_point(data = marcados, 
              aes(x = decimalLongitude, y = decimalLatitude, 
                  )) +
   theme(legend.title = element_blank()) +
   labs(x = "Longitude", y = "Latitude", 
        title = expression(italic("Balaenoptera physalus")))